language: objective-c
osx_image: xcode8.3
branches:
  only:
    - master
    - /[0-9]+\.[0-9]+\.[0-9]+/
install:
  - gem install fastlane --no-ri --no-doc --no-document
  - gem install cocoapods --no-ri --no-doc --no-document
script:
  - bash ./scripts/travis.sh
deploy:
  provider: script
  script: ./scripts/release.sh
  on:
    tags: true
