fastlane_version "2.63.0"
default_platform :ios

platform :ios do

  ####### Testing #######

  desc "Runs all the tests"
  lane :tests do
    scan(
      workspace: "Example/Swen.xcworkspace",
      scheme: "Swen-Example",
      devices: ["iPhone 7 Plus"],
      code_coverage: true,
      clean: true
    )
  end

  ####### Code Coverage #######

  lane :code_coverage do
    slather(
        scheme: 'Swible-Example',
        proj: 'Example/Swible.xcodeproj',
        workspace: 'Example/Swible.xcworkspace',
        coveralls: true,
        circleci: true,
        ignore: 'Example/*',
        binary_basename: 'Swible'
     )
  end

end
