fastlane_version "2.28.4"
default_platform :ios

platform :ios do

  before_all do
    ensure_git_status_clean
    xcversion version: "~> 8.3"
  end

  after_all do |lane, options|
    clean_up
  end

  error do |lane, exception|
    clean_up
  end


  ####### Private Lanes #######

  private_lane :clean_up do
    clean_build_artifacts

    reset_git_repo(
        skip_clean: true
    )
  end


  ####### Testing #######

  desc "Runs all the tests"
  lane :tests do
    scan(
      workspace: "Example/Swen.xcworkspace",
      scheme: "Swen-Example",
      devices: ["iPhone 7 Plus"],
      code_coverage: true,
      clean: true
    )
    sh "curl -s https://codecov.io/bash | bash -s -- -J 'Swen'"
  end

end
